// Copyright 2024 Itential Inc. All Rights Reserved
// Unauthorized copying of this file, via any medium is strictly prohibited
// Proprietary and confidential

package runners

import (
	"os"
	"path/filepath"

	"github.com/itential/ipctl/internal/flags"
	"github.com/itential/ipctl/internal/utils"
	"github.com/itential/ipctl/pkg/config"
	"github.com/itential/ipctl/pkg/logger"
)

type PushAction struct {
	Name     string
	Filename string
	Data     any
	Config   *config.Config
	Options  flags.AssetPushCommon
}

func (p PushAction) Do() error {
	logger.Trace()

	repo, err := GetRepository(p.Name, p.Config)
	if err != nil {
		return err
	}

	if p.Options.Reference != "" {
		repo.Reference = p.Options.Reference
	}

	path, err := CloneRepository(repo)
	if err != nil {
		return err
	}
	defer os.Remove(path)

	if err := utils.WriteJsonToDisk(p.Data, p.Filename, path); err != nil {
		return err
	}

	msg := p.Options.Message
	if msg == "" {
		msg = "autogenerated message"
	}

	if err := CommitAndPushRepo(repo, path, msg); err != nil {
		return err
	}

	return nil
}

type PullAction struct {
	Name     string
	Filename string
	Data     any
	Config   *config.Config
	Options  flags.AssetPullCommon
}

func (p PullAction) Do() ([]byte, error) {
	logger.Trace()

	repo, err := GetRepository(p.Name, p.Config)
	if err != nil {
		return nil, err
	}

	if p.Options.Reference != "" {
		repo.Reference = p.Options.Reference
	}

	path, err := CloneRepository(repo)
	if err != nil {
		return nil, err
	}

	path = filepath.Join(path, p.Options.Path, p.Filename)

	return utils.ReadFromFile(path)
}
