---
version: 2

before:
  hooks:
    - make clean
    - go mod tidy

snapshot:
  version_template: "{{ .Version }}"

builds:
  - id: default
    ldflags:
      - -s -w
      - -X github.com/itential/ipctl/internal/metadata.Build={{ .Env.BUILD }}
      - -X github.com/itential/ipctl/internal/metadata.Version={{ .Tag }}
